resolver: lts-10.09

# lts-9.21
# ghc-8.0.2

# lts-10.09
# ghc-8.2.2

# lts-11.22
# ghc-8.2.2

# lts-12.26
# ghc-8.4.4

# lts-14.25
# ghc-8.6.5


flags: {}
packages:
- .
extra-deps:
- directory-1.3.2.2
- parsec-3.1.13.0
- primitive-0.6.4.0
- process-1.4.3.0

- Euterpea-2.0.6
- HCodecs-0.5.1
- PortMidi-0.1.6.1
- arrows-0.4.4.2
- Stream-0.4.7.2
- lazysmallcheck-0.6

allow-newer: true
