flags: {}
packages:
- .
extra-deps:
- directory-1.3.2.2
- parsec-3.1.13.0
- primitive-0.6.4.0

# - AlgoRhythm-0.1.0.0
- Euterpea-2.0.6
- HCodecs-0.5.1
- PortMidi-0.1.6.1
- arrows-0.4.4.2
- Stream-0.4.7.2
- lazysmallcheck-0.6

resolver: lts-9.17
